on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      NOCO_URL:
        required: true
      NOCO_API_KEY:
        required: true
      NOCO_BASE_ID:
        required: true

name: Action - Test

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests
        run: python -m unittest discover -v -s ./tests -p "test_*.py"
        env:
          NOCO_URL: ${{ secrets.NOCO_URL }}
          NOCO_API_KEY: ${{ secrets.NOCO_API_KEY }}
          NOCO_BASE_ID: ${{ secrets.NOCO_BASE_ID }}
