name: Unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Unit tests on Cloud
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.8", "3.12"]
        environment: ["cloud"]

    uses: ./.github/workflows/action-test.yml
    with:
      python-version: ${{ matrix.python-version }}
      environment: ${{ matrix.environment }}
    secrets:
      NOCO_URL: ${{ secrets.NOCO_URL }}
      NOCO_API_KEY: ${{ secrets.NOCO_API_KEY }}
      NOCO_BASE_ID: ${{ secrets.NOCO_BASE_ID }}
